# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

default: &default
  # Postgresql local login details
  pg_user1: <%= ENV.fetch("PGUSER1") %>
  pg_password: <%= ENV.fetch("PGPASSWORD") %>

  braintree_environment: <%= ENV.fetch("BRAINTREE_ENVIRONMENT") %>
  braintree_merchant_id: <%= ENV.fetch("BRAINTREE_MERCHANT_ID") %>
  braintree_public_key: <%= ENV.fetch("BRAINTREE_PUBLIC_KEY") %>
  braintree_private_key: <%= ENV.fetch("BRAINTREE_PRIVATE_KEY") %>

  mailgun_api_key: <%= ENV.fetch("MAILGUN_API_KEY") %>
  mailgun_smtp_hostname: <%= ENV.fetch("MAILGUN_SMTP_HOSTNAME") %>
  mailgun_domain: <%= ENV.fetch("MAILGUN_DOMAIN") %>
  mailgun_username: <%= ENV.fetch("MAILGUN_USERNAME") %>
  mailgun_password: <%= ENV.fetch("MAILGUN_PASSWORD") %>
  mail_from: <%= ENV.fetch("MAIL_FROM") %>

development:
  <<: *default
  secret_key_base: 8f491c6ac43364a880d910edfb03ce085906d5c63c298b7c51f2278a1d53197d81e81baad5b6e1ae712d6ed0b32b8be863905c8f074ada74a9b6eb695d44d8c7
#   Not in use
#  redis_server: localhost
#  redis_port: 6379
#  redis_cache_database: 0
#  redis_cache_namespace: '056redis'

test:
  <<: *default
  secret_key_base: b6ff2feb279697dc666687f0ea0691fe61ef73067a1ccf1dbe85912af4c00284f046fdf26edd8f295c10d2fef55f17235b065df2bdb52abf1d71d63bd691eeb2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
